"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv  # ADD THIS

# Load environment variables from .env file
load_dotenv()  # ADD THIS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable with fallback for development
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-only-for-local')  # CHANGED

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable
DEBUG = os.environ.get('DEBUG', 'False') == 'True'  # CHANGED

# Render provides this environment variable
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')

# Localhost for development
ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # CHANGED

# Add Render hostname if available
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'scheduling',
    'leaves',
    'core',
    'whitenoise.runserver_nostatic',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # REMOVED problematic custom middleware - they cause issues on Render
]

# Session settings
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = True

# CSRF settings for production
CSRF_COOKIE_SECURE = not DEBUG  # Secure only in production
CSRF_TRUSTED_ORIGINS = []  # Will be set below

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # REMOVED: 'accounts.context_processors.session_info', - causes errors
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Use PostgreSQL on Render, SQLite locally
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Production database (PostgreSQL on Render)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # Development database (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Disable file uploads or use temporary storage
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# For free tier, disable media files or use cloud storage
# Option 1: Disable media uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = '/tmp/media/'  # Temporary directory

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MANIFEST_STRICT = False  # Helps with missing files in production

# Security settings for production
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Other security
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # Add Render URL to CSRF trusted origins
    if RENDER_EXTERNAL_HOSTNAME:
        CSRF_TRUSTED_ORIGINS = [
            f'https://{RENDER_EXTERNAL_HOSTNAME}',
            f'http://{RENDER_EXTERNAL_HOSTNAME}',  # For initial setup
        ]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.Employee'

# Authentication URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

# Email configuration (for password reset, etc.)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Development
if not DEBUG:
    # Production email settings (configure these on Render)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# ===== PYTHONANYWHERE DETECTION =====
# Automatically detect PythonAnywhere and adjust settings
import sys

def is_pythonanywhere():
    """Check if running on PythonAnywhere"""
    return 'pythonanywhere' in os.environ.get('HOME', '')

if is_pythonanywhere():
    print("✓ Running on PythonAnywhere - Adjusting settings...")
    
    # 1. Add PythonAnywhere domain to allowed hosts
    PYTHONANYWHERE_DOMAIN = 'khim0402.pythonanywhere.com'  # CHANGE THIS
    if PYTHONANYWHERE_DOMAIN not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(PYTHONANYWHERE_DOMAIN)
        ALLOWED_HOSTS.append(f'www.{PYTHONANYWHERE_DOMAIN}')
    
    # 2. Use Render PostgreSQL if available, otherwise keep current
    RENDER_DB_URL = os.environ.get('RENDER_DB_URL')  # Will set on PythonAnywhere
    
    if RENDER_DB_URL:
        # Override with Render PostgreSQL
        DATABASES = {
            'default': dj_database_url.config(
                default=RENDER_DB_URL,
                conn_max_age=600,
                ssl_require=True
            )
        }
        print(f"✓ Using Render PostgreSQL: {RENDER_DB_URL.split('@')[1] if '@' in RENDER_DB_URL else 'Connected'}")
    
    # 3. Adjust static/media paths for PythonAnywhere
    STATIC_ROOT = '/home/khim0402/work_shift_scheduler/staticfiles'  # CHANGE USERNAME
    MEDIA_ROOT = '/home/khim0402/work_shift_scheduler/media'  # CHANGE USERNAME
    
    # 4. PythonAnywhere handles SSL at proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 5. Disable debug mode
    DEBUG = False
    
    print("✓ PythonAnywhere settings applied successfully")